name: Package Candy Box 2
on:
  push:
    branches:
      - "candy-box-2"
  release:
    types:
      - created

jobs:
  archive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Archive
        run: |
          cd worlds
          zip -r candybox2.apworld candybox2/
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: "worlds/candybox2.apworld"
          name: 'candybox2.apworld'
#  release:
#    runs-on: ubuntu-latest
#    if: ${{ github.event_name == 'push' }}
#    needs:
#      - archive
#    steps:
#      - uses: actions/download-artifact@v4
#        with:
#          name: 'candybox2.apworld'
#      - uses: "marvinpinto/action-automatic-releases@latest"
#        with:
#          repo_token: "${{ secrets.GITHUB_TOKEN }}"
#          automatic_release_tag: "latest"
#          prerelease: true
#          title: "Latest Development Build"
#          files: candybox2.apworld
  release-to-created-release:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'release' }}
    permissions:
      contents: write
    needs:
      - archive
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: 'candybox2.apworld'
      - name: Upload Release
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ github.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          -H "Content-Type: application/octet-stream" \
          "https://uploads.github.com/repos/${{ github.event.repository.owner.login }}/${{ github.event.repository.name }}/releases/${{ github.event.release.id }}/assets?name=candybox2.apworld" \
          --data-binary "@candybox2.apworld"
